[package]
name = "dwallet_utils"
edition = "2024"
license = "BSD-3-Clause-Clear"
authors = ["dWallet Labs, Ltd. <dev@dwalletlabs.com>"]

[dependencies]
ika_dwallet_2pc_mpc = { local = "../ika_dwallet_2pc_mpc"}

[addresses]
dwallet_utils = "0x0"

[dev-dependencies]

[dev-addresses]
