packages:
  - 'sdk/**'
  - 'examples/keyspring/backend'
  - 'examples/multisig-bitcoin/frontend'
  - '!**/dist/**'
  - '!**/.next/**'
  - '!docs/**'
  - '!sdk/typescript/plugin'
  - '!sdk/plugins/sui'
  - '!sdk/plugins/sui/source'
  - '!sdk/plugins/sui/destination'
  - '!sdk/plugins/sui/publisher'
  - '!sdk/plugins/solana'
  - '!sdk/plugins/solana/destination'
  - '!sdk/plugins/solana/publisher'
  - '!sdk/plugins/ethereum'
  - '!sdk/plugins/ethereum/destination'
  - '!sdk/plugins/ethereum/publisher'
  - '!sdk/plugins/bitcoin'
  - '!sdk/plugins/bitcoin/destination'
  - '!sdk/plugins/bitcoin/publisher'
