#[test_only]
module recovery::solana_msg_tests;

use recovery::solana_msg;
use recovery::sweep_intent;

// === Fixture ===
// A real `MessageV0` produced by `@solana/web3.js`'s `TransactionMessage`
// with a single `SystemProgram::Transfer(100 lamports)` from a synthetic
// `from` account to `to`. Generated by `scripts/gen-solana-fixture.ts` (kept
// as a one-shot snippet — bytes are deterministic for the embedded keys).
//
// Decomposition:
//   80                      version v0
//   01 00 01                header: 1 required sig, 0 ro_signed, 1 ro_unsigned
//   03                      account count
//   58b2…0d990 (32B)        account[0] = from (writable signer = payer)
//   b655…5299c (32B)        account[1] = to (writable, unsigned)
//   0000…0000  (32B)        account[2] = SystemProgram (readonly unsigned)
//   3333…3333  (32B)        recent blockhash (placeholder)
//   01                      ix count
//   02                      program_id_index = 2 (SystemProgram)
//   02 00 01                ix accounts: [from, to]
//   0c                      data length
//   02000000 6400000000000000   data = Transfer (u32 LE) | 100 lamports (u64 LE)
//   00                      0 address-table lookups
const TRANSFER_FIXTURE: vector<u8> = x"800100010358b2b406dbfb8a70baf0b185303efbf41cabb70a839f1effee31333c6fb0d990b655ba304ac0a45446dbf96097c694c6591ed0d48495fd18496928d89775299c0000000000000000000000000000000000000000000000000000000000000000333333333333333333333333333333333333333333333333333333333333333301020200010c02000000640000000000000000";

const FROM_PUBKEY: vector<u8> = x"58b2b406dbfb8a70baf0b185303efbf41cabb70a839f1effee31333c6fb0d990";
const TO_PUBKEY: vector<u8> = x"b655ba304ac0a45446dbf96097c694c6591ed0d48495fd18496928d89775299c";
const SYSTEM_PROGRAM: vector<u8> = x"0000000000000000000000000000000000000000000000000000000000000000";

// === Parser tests ===

#[test]
fun parse_real_transfer_fixture() {
    let parsed = solana_msg::parse(TRANSFER_FIXTURE);
    assert!(solana_msg::num_required_signatures(&parsed) == 1, 0);

    let keys = solana_msg::account_keys(&parsed);
    assert!(keys.length() == 3, 1);
    assert!(*keys.borrow(0) == FROM_PUBKEY, 2);
    assert!(*keys.borrow(1) == TO_PUBKEY, 3);
    assert!(*keys.borrow(2) == SYSTEM_PROGRAM, 4);

    let ixs = solana_msg::instructions(&parsed);
    assert!(ixs.length() == 1, 5);
    let ix = ixs.borrow(0);
    assert!(solana_msg::program_id_index(ix) == 2, 6);

    let accs = solana_msg::account_indices(ix);
    assert!(accs.length() == 2, 7);
    assert!(*accs.borrow(0) == 0, 8);
    assert!(*accs.borrow(1) == 1, 9);

    let data = solana_msg::data(ix);
    assert!(data.length() == 12, 10);
    // u32 LE 2 (Transfer) | u64 LE 100 (lamports)
    assert!(solana_msg::read_u32_le(data, 0) == 2, 11);
    assert!(solana_msg::read_u64_le(data, 4) == 100, 12);

    // Helper accessors round-trip.
    assert!(solana_msg::fee_payer(&parsed) == FROM_PUBKEY, 13);
    assert!(solana_msg::program_id(&parsed, ix) == SYSTEM_PROGRAM, 14);
    assert!(solana_msg::account_at(&parsed, ix, 0) == FROM_PUBKEY, 15);
    assert!(solana_msg::account_at(&parsed, ix, 1) == TO_PUBKEY, 16);
}

#[test]
fun read_u64_le_zero() {
    let data: vector<u8> = x"0000000000000000";
    assert!(solana_msg::read_u64_le(&data, 0) == 0, 0);
}

#[test]
fun read_u64_le_max() {
    let data: vector<u8> = x"ffffffffffffffff";
    assert!(solana_msg::read_u64_le(&data, 0) == 0xffffffffffffffff, 0);
}

#[test]
fun read_u32_le_arbitrary() {
    // 0x04030201 in LE bytes.
    let data: vector<u8> = x"01020304";
    assert!(solana_msg::read_u32_le(&data, 0) == 0x04030201, 0);
}

// === Negative parser tests ===

#[test]
#[expected_failure(abort_code = solana_msg::EInvalidVersion)]
fun reject_legacy_version() {
    // First byte not 0x80 → legacy message → reject.
    let bytes: vector<u8> = x"01";
    let _ = solana_msg::parse(bytes);
}

#[test]
#[expected_failure(abort_code = solana_msg::EAddressTableLookupsNotSupported)]
fun reject_address_table_lookups() {
    // Same shape as TRANSFER_FIXTURE but the trailing lookup-count byte is
    // 1 instead of 0, and we append a stub lookup entry. Hand-crafted to
    // exercise the lookup-rejection path.
    //
    // Header through ix data is identical (last byte before lookups = data
    // tail 0x00). Then: lookup_count=01, table_pubkey=32B 0xee, writable=00,
    // readonly=00.
    let bytes: vector<u8> = x"800100010358b2b406dbfb8a70baf0b185303efbf41cabb70a839f1effee31333c6fb0d990b655ba304ac0a45446dbf96097c694c6591ed0d48495fd18496928d89775299c0000000000000000000000000000000000000000000000000000000000000000333333333333333333333333333333333333333333333333333333333333333301020200010c020000006400000000000000010001eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee0000";
    let _ = solana_msg::parse(bytes);
}

#[test]
#[expected_failure(abort_code = solana_msg::EUnexpectedEof)]
fun reject_truncated_message() {
    // Just the version byte — parser should hit EOF reading the header.
    let bytes: vector<u8> = x"80";
    let _ = solana_msg::parse(bytes);
}

#[test]
#[expected_failure(abort_code = solana_msg::ETrailingBytes)]
fun reject_trailing_bytes() {
    // Append a byte after the valid fixture's final lookup-count — should be
    // rejected (off != n at end-of-parse).
    let mut bytes = TRANSFER_FIXTURE;
    bytes.push_back(0xff);
    let _ = solana_msg::parse(bytes);
}

// === Intent extraction tests ===

#[test]
fun extract_intent_from_transfer_fixture() {
    let intent = sweep_intent::from_message_bytes(TRANSFER_FIXTURE);
    assert!(*sweep_intent::fee_payer(&intent) == FROM_PUBKEY, 0);
    let ixs = sweep_intent::ixs(&intent);
    assert!(ixs.length() == 1, 1);
    // Equality of intents — we don't expose the variant fields directly,
    // so re-derive an "expected" intent from the same bytes and compare.
    let expected = sweep_intent::from_message_bytes(TRANSFER_FIXTURE);
    assert!(intent == expected, 2);
}

#[test]
fun intent_hash_is_stable_across_calls() {
    let intent_a = sweep_intent::from_message_bytes(TRANSFER_FIXTURE);
    let intent_b = sweep_intent::from_message_bytes(TRANSFER_FIXTURE);
    let intents_a = vector[intent_a];
    let intents_b = vector[intent_b];
    assert!(sweep_intent::hash_intents(&intents_a) == sweep_intent::hash_intents(&intents_b), 0);
}

#[test]
fun intent_hash_is_32_bytes() {
    let intent = sweep_intent::from_message_bytes(TRANSFER_FIXTURE);
    let intents = vector[intent];
    assert!(sweep_intent::hash_intents(&intents).length() == 32, 0);
}
