// Copyright (c) dWallet Labs, Ltd.
// SPDX-License-Identifier: BSD-3-Clause-Clear

/**
 * Re-exports generated Move call builders and BCS types for the OWS
 * Policy Engine contract.
 *
 * These are auto-generated by `@mysten/codegen` from the Move sources
 * in `contract/`. Run `pnpm codegen` to regenerate after Move changes.
 */

export * as policyEngine from '../generated/ika_ows_policy/policy_engine.js';
export * as rateLimit from '../generated/ika_ows_policy/rate_limit.js';
export * as expiry from '../generated/ika_ows_policy/expiry.js';
export * as senderAllowlist from '../generated/ika_ows_policy/sender_allowlist.js';
export * as allowedAlgorithms from '../generated/ika_ows_policy/allowed_algorithms.js';
export * as spendingBudget from '../generated/ika_ows_policy/spending_budget.js';
export * as targetFilter from '../generated/ika_ows_policy/target_filter.js';
export * as timeDelay from '../generated/ika_ows_policy/time_delay.js';
