/**
 * One-shot fixture generator for the Move-side `assertion::verify` happy-path
 * test. Generates a P-256 keypair, fabricates an authenticator_data and
 * clientDataJSON whose challenge equals a known SHA-256 digest, signs the
 * concatenation with the key, and prints all bytes formatted as Move literals.
 *
 * Re-run if the assertion-verification test ever needs to be regenerated:
 *   bun scripts/gen-webauthn-fixture.ts
 *
 * The fixture is otherwise stable; we use a fixed seed so output is
 * deterministic across runs.
 */
import { p256 } from '@noble/curves/nist.js';
import { sha256 } from '@noble/hashes/sha2.js';
import { concatBytes } from '@noble/hashes/utils.js';

import { spkiToCompressedP256 } from '../src/passkey/spki';

const enc = new TextEncoder();

// Deterministic 32-byte seed -> deterministic key -> deterministic signature.
const seed = new Uint8Array(32);
for (let i = 0; i < 32; i++) seed[i] = i + 1;

const sk = seed;
const compressedPubKey = p256.getPublicKey(sk, true);

// Operation hash the challenge will commit to. In the real flow this is
// produced by `buildProposeChallenge(...)` etc.; the Move side only cares that
// the bytes match what `assertion::verify` recomputes via `challenges::*`.
const expectedChallenge = sha256(enc.encode('recovery::test::challenge'));

const clientDataJSON = enc.encode(
	`{"type":"webauthn.get","challenge":"${toBase64UrlNoPad(expectedChallenge)}","origin":"https://recovery.example","crossOrigin":false}`,
);

// Fake but well-formed authenticator data: 32-byte rpIdHash || flags(0x01 = UP) || signCount(0x00000001).
const rpIdHash = sha256(enc.encode('recovery.example'));
const authenticatorData = concatBytes(
	rpIdHash,
	new Uint8Array([0x01]),
	new Uint8Array([0x00, 0x00, 0x00, 0x01]),
);

// WebAuthn signs `authenticator_data || sha256(clientDataJSON)` after a
// SHA-256 hash. `secp256r1_verify(sig, pk, signed, SHA256=1)` recomputes that
// same SHA-256 internally, so we pass the already-hashed digest to `p256.sign`
// here (noble defaults to "msg is already a digest" mode for ECDSA).
const signedPreimage = concatBytes(authenticatorData, sha256(clientDataJSON));
const digest = sha256(signedPreimage);
const sigObj = p256.sign(digest, sk, { lowS: true });
const rawSig = sigObj.toCompactRawBytes();

console.log('// Generated by sui/packages/sdk/scripts/gen-webauthn-fixture.ts');
console.log('// Re-run that script if you need to refresh these vectors.');
console.log();
console.log(`// public_key (compressed secp256r1, 33 bytes)`);
emit('PUB_KEY', compressedPubKey);
console.log(`// authenticator_data (37 bytes)`);
emit('AUTH_DATA', authenticatorData);
console.log(`// client_data_json (${clientDataJSON.length} bytes)`);
emit('CLIENT_DATA_JSON', clientDataJSON);
console.log(`// signature (raw r||s, 64 bytes)`);
emit('SIGNATURE', rawSig);
console.log(`// expected_challenge (32 bytes)`);
emit('EXPECTED_CHALLENGE', expectedChallenge);

function emit(name: string, bytes: Uint8Array): void {
	const lines = [`const ${name}: vector<u8> = vector[`];
	let row = '    ';
	bytes.forEach((b, i) => {
		row += `0x${b.toString(16).padStart(2, '0')}, `;
		if ((i + 1) % 12 === 0) {
			lines.push(row.trimEnd());
			row = '    ';
		}
	});
	if (row.trim()) lines.push(row.trimEnd());
	lines.push('];');
	console.log(lines.join('\n'));
	console.log();
}

function toBase64UrlNoPad(bytes: Uint8Array): string {
	let s = '';
	for (const b of bytes) s += String.fromCharCode(b);
	return btoa(s).replaceAll('+', '-').replaceAll('/', '_').replace(/=+$/, '');
}

// Sanity: spkiToCompressedP256 import keeps the function alive in the bundle
// even though we don't strictly need it here; helpful if we extend the script.
void spkiToCompressedP256;
