name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  RUSTDOCFLAGS: -Dwarnings
  RUST_BACKTRACE: 1
  # Change to specific Rust release to pin or `stable` for the latest stable version.
  rust_stable: 1.88
  rust_nightly: nightly
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  GH_DEPLOY_KEY: ${{ secrets.GH_DEPLOY_KEY }}

jobs:
  build:
    if: github.event_name == 'push'
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup SSH for manual git
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.GH_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Globally rewrite any GitHub HTTPS to SSH
        run: |
          git config --global url."git@github.com:".insteadOf "https://github.com/"
      - name: Install Rust ${{ env.rust_stable }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_stable }}
          targets: x86_64-unknown-linux-gnu
      - name: Install Target
        run: rustup target add x86_64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: RUSTFLAGS="-D warnings" cargo build --bin ika --target-dir . --profile dev --target x86_64-unknown-linux-gnu

  fmt:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup SSH for manual git
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.GH_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Globally rewrite any GitHub HTTPS to SSH
        run: |
          git config --global url."git@github.com:".insteadOf "https://github.com/"
      - name: Install Rust 1.88
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.88
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Fmt Check
        run: cargo fmt -- --check
      - name: Fmt Check - Wasm
        run: cargo fmt -- --check
        working-directory: sdk/ika-wasm
  clippy:
    if: github.event_name == 'push'
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup SSH for manual git
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.GH_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Globally rewrite any GitHub HTTPS to SSH
        run: |
          git config --global url."git@github.com:".insteadOf "https://github.com/"
      - name: Install Rust 1.88
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.88
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Run Clippy
        run: cargo clippy --all-features -- -D warnings

  cargo-check:
    name: Cargo Test Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup SSH for manual git
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.GH_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Globally rewrite any GitHub HTTPS to SSH
        run: |
          git config --global url."git@github.com:".insteadOf "https://github.com/"
      - name: Install Rust ${{ env.rust_stable }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_stable }}
          targets: x86_64-unknown-linux-gnu
      - name: Install Target
        run: rustup target add x86_64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
      - name: cargo check (ika-core tests)
        run: cargo check -p ika-core --features test-utils --tests --target x86_64-unknown-linux-gnu
