name: Publish Chaos Test Image

on:
  workflow_dispatch:
    inputs:
      cargo_build_flags:
        description: 'Build flags for cargo'
        required: false
        default: '--no-default-features'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: dwallet-labs
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        env:
          CARGO_BUILD_FLAGS: ${{ github.event.inputs.cargo_build_flags }}
        run: |
          IMAGE_NAME=ghcr.io/dwallet-labs/dwallet-network/ika:latest
          cd sdk/typescript/test/chaos-test
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
