name: Integration Tests CI

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1
  # Change to specific Rust release to pin or `stable` for the latest stable version.
  rust_stable: 1.90
  rust_nightly: nightly
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  GH_DEPLOY_KEY: ${{ secrets.GH_DEPLOY_KEY }}

jobs:
  run-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH for manual git
        if: env.GH_DEPLOY_KEY
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.GH_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Globally rewrite any GitHub HTTPS to SSH
        if: env.GH_DEPLOY_KEY
        run: |
          git config --global url."git@github.com:dwallet-labs/cryptography-private".insteadOf "https://github.com/dwallet-labs/cryptography-private"

      - name: Install Rust ${{ env.rust_stable }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_stable }}
          targets: x86_64-unknown-linux-gnu
      - name: Install Target
        run: rustup target add x86_64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
      - name: Run Integration Tests
        run: cargo test --profile release --no-default-features --color=always --lib dwallet_mpc::integration_tests